### ISSUE TITLE
route360 js library should be made browser and framework agnostic

### ISSUE THREAD

**Issue by therealgilles** [route360/r360-angular#4]
Right now, the route360 js library depends on having a browser available, and the r360-angular library depends on the angular framework. It would be best to make the library browser and framework agnostic.

There are a lot of javascript frameworks out there, and some of them work without a browser. Node and react-native come to mind. They do not have a window object, nor window.document, jQuery is not available either. When it comes to maps, the core library should provide as much functionality as possible while not using any specific map library. Ideally it should provide complete GeoJSON polygons (with holes), and circles if desired, ready to be displayed.

The library should be written with the least amount of dependency possible. Interfaces with maps, http..., should abstracted into separate functions that can easily be replaced based on the developer needs/environment.

**Comment by silberjan** [comment]
Hi @therealgilles,
thank you for your ideas. Currently our js lib is meant to be used on the frontend. The most recent version only has leaflet and jquery left as deps. We are working on refactoring the lib to also get rid of jquery. However this is a time consuming process (PRs are always welcome ;) The angular-lib is just an integreation of our js lib in angular1. 
To use r360 on the server side you already may use our [Python](https://github.com/route360/r360-py) or [java](https://github.com/route360/r360-java) lib.
A r360-nodejs lib is currently not in development, however we will discuss your proposal internally.
